# Generated by Django 2.2.1 on 2019-06-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190619_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tournament'),
        ),
    ]
