# Generated by Django 2.2.1 on 2019-06-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_teams', models.IntegerField(default=0)),
                ('number_of_adjudicators', models.IntegerField(default=0)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('number_of_adjudicators_in_a_room', models.IntegerField(default=0)),
                ('motion', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tournament')),
            ],
        ),
    ]
