# Generated by Django 2.2.1 on 2019-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number_of_adjudicators_in_a_room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='number_of_rooms',
            field=models.IntegerField(),
        ),
    ]
