# Generated by Django 2.2.1 on 2019-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number_of_adjudicators',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='number_of_teams',
            field=models.IntegerField(),
        ),
    ]
