# Generated by Django 2.2.1 on 2019-06-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190620_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='team1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='team2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='team3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='team4',
            field=models.CharField(max_length=100),
        ),
    ]
