# Generated by Django 2.2.1 on 2019-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190620_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='team2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='team3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='team4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
