# Generated by Django 2.2.1 on 2019-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190620_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adjudicators',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
